

function getURLParameter(name) {
    return decodeURIComponent(
        (RegExp(name + '=' + '(.+?)(&|$)').exec(location.search) || [, null])[1] || ''
    );
}


function replace_text(lang, text) {
    x = document.getElementById(text);
    if (x) {
        x.innerHTML = translation[lang][text];
    } else {
        console.log("element not Found: " + text);
    }
}

function alert_string(lang, text) {
    return translation[lang][text] + "\n\n";
}

function translation_available(lang) {
    if (translation[lang]) {
        return lang;
    } else {
        console.log("translation not Found: " + lang);
        return "source";
    }
}

function detect_language() {
    var detected_language = navigator.languages && navigator.languages[0] || navigator.language || navigator.userLanguage;
    if (detected_language.length > 3) {
        detected_language = detected_language[0] + detected_language[1];
    };
    if (jQuery.inArray(detected_language, ['ar', 'he', 'fa', 'ur']) >= 0) {
        $('html').attr('DIR', 'RTL');
    }
    return translation_available(detected_language);
}


var translation = {
    source: {
        a1: `App Market`,
        a2: `XXXLOVE - the best porn app.`,
        a3: `PH Company`,
        a4: `48.7K reviews`,
        a5:`Downloads`,
        a6:`Rated for 18+`,
        a7:`Install`,
        a8:`   <img src="/assets/images/bookmark.svg"> Add to Wishlist`,
        a9:`Contains Ads`,
        a10:`About this app <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`The best porn app for Android. Watch new hot videos every day 🔥 🔥 🔥
        <br>
        Only high-quality content, a player without lags, fast loading and endless emotions`,
        a12:`Updated on`,
        a13:`Data safety`,
        a14:`Developers can show information here about how their app collects and uses your data.`,
        a15:`Ratings and reviews`,
        a16:`Ratings and reviews are verified <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K reviews`,
        a18:`Sanjay Kumar`,
        a19:`This app is so good! We are waiting for new HOT content!`,
        a20:`Eduard Tereshko`,
        a21:`High quality content! After watching the first video, it is impossible to stop at
        the second`,
        a22:`Asha Devi`,
        a23:` I'm really love this app. 💦💦💦 `,

    },
    en: {
        a1: `App Market`,
        a2: `XXXLOVE - the best porn app.`,
        a3: `PH Company`,
        a4: `48.7K reviews`,
        a5:`Downloads`,
        a6:`Rated for 18+`,
        a7:`Install`,
        a8:`   <img src="/assets/images/bookmark.svg"> Add to Wishlist`,
        a9:`Contains Ads`,
        a10:`About this app <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`The best porn app for Android. Watch new hot videos every day 🔥 🔥 🔥
        <br>
        Only high-quality content, a player without lags, fast loading and endless emotions`,
        a12:`Updated on`,
        a13:`Data safety`,
        a14:`Developers can show information here about how their app collects and uses your data.`,
        a15:`Ratings and reviews`,
        a16:`Ratings and reviews are verified <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K reviews`,
        a18:`Sanjay Kumar`,
        a19:`This app is so good! We are waiting for new HOT content!`,
        a20:`Eduard Tereshko`,
        a21:`High quality content! After watching the first video, it is impossible to stop at
        the second`,
        a22:`Asha Devi`,
        a23:` I'm really love this app. 💦💦💦 `,
    },

    de: {
        a1: `App-Markt`,
        a2:`XXXLOVE – die beste Porno-App.`,
        a3:`PH-Unternehmen`,
        a4: `48.7K Bewertungen`,
        a5:`Downloads`,
        a6:`Freigegeben für 18+`,
        a7:`Installieren`,
        a8:` <img src="/assets/images/bookmark.svg"> Zur Wunschliste hinzufügen`,
        a9:`Enthält Werbung`,
        a10:`Über diese App <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Die beste Porno-App für Android. Sieh dir jeden Tag neue heiße Videos an 🔥 🔥 🔥
        <br>
        Nur qualitativ hochwertige Inhalte, ein Spieler ohne Verzögerungen, schnelles Laden und endlose Emotionen`,
        a12:`Aktualisiert am`,
        a13:`Datensicherheit`,
        a14:`Entwickler können hier Informationen darüber anzeigen, wie ihre App Ihre Daten sammelt und verwendet.`,
        a15:`Bewertungen und Rezensionen`,
        a16:`Bewertungen und Rezensionen sind verifiziert <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K Bewertungen`,
        a18:`Sanjay Kumar`,
        a19:`Diese App ist so gut! Wir warten auf neue HEISSE Inhalte!`,
        a20:`Eduard Tereshko`,
        a21:`Hochwertiger Inhalt! Nach dem Ansehen des ersten Videos ist es unmöglich, damit aufzuhören
        der zweite`,
        a22:`Asha Devi`,
        a23:` Ich liebe diese App wirklich. 💦💦💦 `,
    },
    fr: {
        a1 : "Marché des applications",
        a2 : `XXXLOVE - la meilleure application porno.`,
        a3 : "Société PH",
        a4 : "48 700 avis",
        a5:`Téléchargements`,
        a6:`Évalué pour 18+`,
        a7:`Installer`,
        a8:` <img src="/assets/images/bookmark.svg"> Ajouter à la liste de souhaits`,
        a9:`Contient des publicités`,
        a10:`À propos de cette application <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`La meilleure application porno pour Android. Regardez de nouvelles vidéos chaudes tous les jours 🔥 🔥 🔥
        <br>
        Uniquement du contenu de haute qualité, un lecteur sans décalage, un chargement rapide et des émotions sans fin`,
        a12:`Mise à jour le`,
        a13:`Sécurité des données`,
        a14 :`Les développeurs peuvent afficher ici des informations sur la manière dont leur application collecte et utilise vos données.`,
        a15:`Notes et avis`,
        a16:`Les notes et les avis sont vérifiés <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K commentaires`,
        a18:`Sanjay Kumar`,
        a19:`Cette application est tellement bonne ! Nous attendons du nouveau contenu HOT!`,
        a20:`Eduard Tereshko`,
        a21:`Contenu de haute qualité ! Après avoir visionné la première vidéo, impossible de s'arrêter à
        le deuxième`,
        a22:`Asha Devi`,
        a23:` J'adore vraiment cette application. 💦💦💦`,
    },
    pt: {
        a1: "Mercado de aplicativos",
        a2: `XXXLOVE - o melhor aplicativo pornô.`,
        a3: `Empresa PH`,
        a4: `48,7 mil comentários`,
        a5:`Downloads`,
        a6:`Avaliado para maiores de 18 anos`,
        a7:`Instalar`,
        a8:` <img src="/assets/images/bookmark.svg"> Adicionar à lista de desejos`,
        a9:`Contém anúncios`,
        a10:`Sobre este aplicativo <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`O melhor aplicativo pornô para Android. Assista novos vídeos quentes todos os dias 🔥 🔥 🔥
        <br>
        Apenas conteúdo de alta qualidade, um player sem atrasos, carregamento rápido e emoções sem fim`,
        a12:`Atualizado em`,
        a13: `Segurança de dados`,
        a14:`Os desenvolvedores podem mostrar aqui informações sobre como o aplicativo deles coleta e usa seus dados.`,
        a15:`Classificações e comentários`,
        a16:`As classificações e avaliações são verificadas <img src="/assets/images/info.png" alt="">`,
        a17:`48,7 mil comentários`,
        a18:`Sanjay Kumar`,
        a19:`Este aplicativo é tão bom! Estamos esperando por novos conteúdos QUENTES!`,
        a20:`Eduard Tereshko`,
        a21:`Conteúdo de alta qualidade! Depois de ver o primeiro vídeo, é impossível parar
        o segundo`,
        a22:`Asha Devi`,
        a23:` Eu realmente amo este aplicativo. 💦💦💦`,
    },
    es: {
        a1: `Mercado de aplicaciones`,
        a2: `XXXLOVE - la mejor aplicación porno.`,
        a3: `Empresa PH`,
        a4: `48.7K reseñas`,
        a5:`Descargas`,
        a6:`Clasificado para mayores de 18`,
        a7:`Instalar`,
        a8:` <img src="/assets/images/bookmark.svg"> Agregar a la lista de deseos`,
        a9:`Contiene anuncios`,
        a10:`Acerca de esta aplicación <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`La mejor aplicación porno para Android. Mira nuevos videos calientes todos los días 🔥 🔥 🔥
        <br>
        Solo contenido de alta calidad, un reproductor sin lag, carga rápida y un sinfín de emociones`,
        a12:`Actualizado el`,
        a13:`Seguridad de datos`,
        a14:`Los desarrolladores pueden mostrar información aquí sobre cómo su aplicación recopila y usa sus datos.`,
        a15:`Valoraciones y reseñas`,
        a16:`Las calificaciones y reseñas están verificadas <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K reseñas`,
        a18:`Sanjay Kumar`,
        a19:`¡Esta aplicación es tan buena! ¡Estamos esperando nuevo contenido CALIENTE!`,
        a20:`Eduard Tereshko`,
        a21:`¡Contenido de alta calidad! Después de ver el primer video, es imposible detenerse en
        el segundo`,
        a22:`Asha Devi`,
        a23:` Me encanta esta aplicación. 💦💦💦`,
    },
    sr: {
        a1: `Апп Маркет`,
        a2: `КСКСКСЛОВЕ - најбоља порно апликација.`,
        a3: `ПХ Цомпани`,
        a4: `48,7 хиљада рецензија`,
        a5:`Преузимања`,
        a6:`Оцијењено за 18+`,
        a7:`Инсталирај`,
        a8:`  <img src="/assets/images/bookmark.svg"> Додај на листу жеља`,
        a9:`Садржи огласе`,
        a10:`О овој апликацији <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: `Најбоља порно апликација за Андроид. Гледајте нове вруће видео записе сваки дан 🔥 🔥 🔥
        <br>
        Само квалитетан садржај, плејер без заостајања, брзо учитавање и бескрајне емоције`,
        a12:`Ажурирано`,
        a13:`Безбедност података`,
        a14: `Програмери могу да прикажу информације овде о томе како њихова апликација прикупља и користи ваше податке.`,
        a15:`Оцене и критике`,
        a16:`Оцене и рецензије су верификоване <img src="/assets/images/info.png" alt="">`,
        a17:`48.7К рецензија`,
        a18:`Сањаи Кумар`,
        a19:`Ова апликација је тако добра! Чекамо нови ВРУЋИ садржај!`,
        a20:`Едуард Терешко`,
        a21:`Садржај високог квалитета! Након гледања првог видеа, немогуће је застати
        други`,
        a22:`Асха Деви`,
        a23:` Заиста волим ову апликацију. 💦💦💦 `,
    },
    ar: {
        a1: `متجر التطبيقات`,
        a2: `XXXLOVE - أفضل تطبيق إباحي.`,
        a3: `شركة PH`,
        a4: `48.7K المراجعات`,
        a5:`التحميلات`,
        a6:`تم تقييمه لـ 18+`,
        a7:`تثبيت`,
        a8:`   <img src="/assets/images/bookmark.svg"> أضف إلى قائمة الامنيات`,
        a9:`يحتوي على إعلانات`,
        a10:`عن هذا التطبيق <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`أفضل تطبيق إباحي للأندرويد. شاهد فيديوهات ساخنة جديدة كل يوم 🔥 🔥 🔥
        <br>
        محتوى عالي الجودة فقط ، لاعب بدون تأخير ، تحميل سريع وعواطف لا تنتهي`,
        a12:`تحديث في`,
        a13:`سلامة البيانات`,
        a14:`يمكن للمطورين عرض المعلومات هنا حول كيفية جمع التطبيق لبياناتك واستخدامها.`,
        a15:`التقييمات والمراجعات`,
        a16:`يتم التحقق من التقييمات والمراجعات<img src="/assets/images/info.png" alt="">`,
        a17:`48.7K المراجعات`,
        a18:`سانجاي كومار`,
        a19:`هذا التطبيق جيد جدا! نحن في انتظار محتوى ساخن جديد`,
        a20:`إدوارد تيريشكو`,
        a21:`محتوى عالي الجودة! بعد مشاهدة الفيديو الأول ، من المستحيل التوقف عند
        الثاني`,
        a22:`آشا ديفي`,
        a23:` أنا حقا أحب هذا التطبيق. 💦💦💦 `,
    },
    ur: {
        a1: `ایپ مارکیٹ`,
        a2: `XXXLOVE - بہترین فحش ایپ۔`,
        a3: `پی ایچ کمپنی`,
        a4: `48.7K جائزے`,
        a5:`ڈاؤن لوڈ`,
        a6:`18+ کے لیے درجہ بندی کی گئی۔`,
        a7:`انسٹال کریں۔`,
        a8:`   <img src="/assets/images/bookmark.svg"> خواہشات کی فہرست میں شامل کرنا`,
        a9:`اشتہارات پر مشتمل ہے۔`,
        a10:`اس ایپ کے بارے میں <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`اینڈرائیڈ کے لیے بہترین فحش ایپ۔ ہر روز نئی گرم ویڈیوز دیکھیں 🔥 🔥 🔥
        <br>
        صرف اعلیٰ معیار کا مواد، بغیر کسی وقفے کے پلیئر، تیز لوڈنگ اور نہ ختم ہونے والے جذبات`,
        a12:`کو اپ ڈیٹ کیا گیا۔`,
        a13:`ڈیٹا کی حفاظت`,
        a14:`ڈیولپرز یہاں اس بارے میں معلومات دکھا سکتے ہیں کہ ان کی ایپ آپ کا ڈیٹا کیسے اکٹھا اور استعمال کرتی ہے۔`,
        a15:`ریٹنگز اور ریویوز`,
        a16:`درجہ بندی اور جائزے کی تصدیق کی جاتی ہے۔ <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K جائزے`,
        a18:`سنجے کمار`,
        a19:`یہ ایپ بہت اچھی ہے! ہم نئے HOT مواد کا انتظار کر رہے ہیں۔!`,
        a20:`ایڈورڈ ٹیرشکو`,
        a21:`اعلی معیار کا مواد! پہلی ویڈیو دیکھنے کے بعد اسے روکنا ناممکن ہے۔
        دوسرا`,
        a22:`آشا دیوی`,
        a23:` مجھے واقعی اس ایپ سے پیار ہے۔ 💦💦💦 `,
    },
    nl: {
        a1: `App-markt`,
        a2: `XXXLOVE - de beste porno-app.`,
        a3: `PH Bedrijf`,
        a4: `48.7K beoordelingen`,
        a5:`Downloads`,
        a6:`Beoordeeld voor 18+`,
        a7:`Installeren`,
        a8:` <img src="/assets/images/bookmark.svg"> Zet op verlanglijst`,
        a9:`Bevat advertenties`,
        a10:`Over deze app <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`De beste porno-app voor Android. Bekijk elke dag nieuwe hete video's 🔥 🔥 🔥
        <br>
        Alleen content van hoge kwaliteit, een speler zonder vertragingen, snel laden en eindeloze emoties`,
        a12:`Bijgewerkt op`,
        a13:`Gegevensveiligheid`,
        a14:`Ontwikkelaars kunnen hier informatie tonen over hoe hun app uw gegevens verzamelt en gebruikt.`,
        a15:`Beoordelingen en beoordelingen`,
        a16:`Beoordelingen en recensies zijn geverifieerd <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K beoordelingen`,
        a18:`Sanjay Kumar`,
        a19:`Deze app is zo goed! We wachten op nieuwe HOT content!`,
        a20:'Eduard Teresjko',
        a21:`Hoge kwaliteit inhoud! Na het zien van de eerste video, is het onmogelijk om te stoppen bij
        de tweede`,
        a22:'Asha Devi',
        a23:` Ik ben echt dol op deze app. `,
    },
    zh: {
        a1: `應用市場`,
        a2: `XXXLOVE - 最好的色情應用。`,
        a3:`PH 公司`,
        a4: `48.7K 評論`,
        a5:`下載`,
        a6: `額定 18+`,
        a7:`安裝`,
        a8:` <img src="/assets/images/bookmark.svg"> 添加到願望清單`,
        a9:`包含廣告`,
        a10:`關於這個應用程序 <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`安卓最好的色情應用。每天觀看新的熱門視頻🔥🔥🔥
        <br>
        只有高質量的內容，沒有延遲的播放器，快速加載和無盡的情感`,
        a12:`更新時間`,
        a13:`數據安全`,
        a14: `開發人員可以在此處顯示有關其應用程序如何收集和使用您的數據的信息。`,
        a15:`評分和評論`,
        a16:`評分和評論已驗證 <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K 評論`,
        a18:`桑傑·庫馬爾`,
        a19: `這個應用太好了！我們正在等待新的 HOT 內容！`,
        a20:`愛德華·捷列什科`,
        a21: `高質量的內容！看完第一個視頻，根本停不下來
        第二個`,
        a22:`Asha Devi`,
        a23: `我真的很喜歡這個應用程序。 💦💦💦`,
    },
    ms: {
        a1: `Pasaran Aplikasi`,
        a2: `XXXLOVE - aplikasi lucah terbaik.`,
        a3: `Syarikat PH`,
        a4: `48.7K ulasan`,
        a5:`Muat Turun`,
        a6:`Dinilai untuk 18+`,
        a7:`Pasang`,
        a8:` <img src="/assets/images/bookmark.svg"> Tambahkan pada Senarai Hajat`,
        a9:`Mengandungi Iklan`,
        a10:`Mengenai aplikasi ini <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Apl lucah terbaik untuk Android. Tonton video panas baharu setiap hari 🔥 🔥 🔥
        <br>
        Hanya kandungan berkualiti tinggi, pemain tanpa ketinggalan, pemuatan pantas dan emosi yang tidak berkesudahan`,
        a12:`Dikemas kini pada`,
        a13:`Keselamatan data`,
        a14:`Pembangun boleh menunjukkan maklumat di sini tentang cara apl mereka mengumpul dan menggunakan data anda.`,
        a15:`Penilaian dan ulasan`,
        a16:`Penilaian dan ulasan disahkan <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K ulasan`,
        a18:`Sanjay Kumar`,
        a19:`Apl ini sangat bagus! Kami sedang menunggu kandungan PANAS baharu!`,
        a20:`Eduard Tereshko`,
        a21:`Kandungan berkualiti tinggi! Selepas menonton video pertama, adalah mustahil untuk berhenti di
        yang kedua`,
        a22:`Asha Devi`,
        a23:` Saya sangat menyukai aplikasi ini. 💦💦💦 `,
    },
    th: {
        a1: 'ตลาดแอป',
        a2: `XXXLOVE - แอพโป๊ที่ดีที่สุด.`,
        a3: `บริษัท PH`,
        a4: `48.7K บทวิจารณ์`,
        a5:`ดาวน์โหลด`,
        a6:`ให้คะแนนสำหรับ 18+`,
        a7: 'ติดตั้ง',
        a8:` <img src="/assets/images/bookmark.svg"> เพิ่มในรายการสิ่งที่อยากได้`,
        a9:`มีโฆษณา`,
        a10:`เกี่ยวกับแอพนี้ <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`แอพโป๊ที่ดีที่สุดสำหรับ Android ดูวิดีโอสุดฮอตทุกวัน 🔥 🔥 🔥
        <br>
        เฉพาะเนื้อหาคุณภาพสูง ผู้เล่นที่ไม่มีความล่าช้า โหลดเร็ว และอารมณ์ที่ไม่รู้จบ`,
        a12: 'อัปเดตเมื่อ',
        a13: 'ความปลอดภัยของข้อมูล',
        a14:`นักพัฒนาสามารถแสดงข้อมูลเกี่ยวกับวิธีการรวบรวมและใช้ข้อมูลของคุณได้ที่นี่`,
        a15:`การให้คะแนนและบทวิจารณ์`,
        a16:`การให้คะแนนและความเห็นได้รับการตรวจสอบแล้ว <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K บทวิจารณ์`,
        a18: 'ซานเจย์ คูมาร์',
        a19:`แอพนี้ดีมาก! เรากำลังรอคอยเนื้อหา HOT ใหม่!`,
        a20:'เอดูอาร์ด เทเรชโก',
        a21: `เนื้อหาคุณภาพสูง! ดูคลิปแรกแล้วหยุดไม่ได้
        ที่สอง`,
        a22:`อาชา เทวี`,
        a23:` ฉันรักแอปนี้มาก 💦💦💦 `,
    },
    id: {
        a1: `Pasar Aplikasi`,
        a2: `XXXLOVE - aplikasi porno terbaik.`,
        a3: `Perusahaan PH`,
        a4: `48.7K ulasan`,
        a5:`Unduhan`,
        a6:`Dinilai untuk 18+`,
        a7:`Instal`,
        a8:` <img src="/assets/images/bookmark.svg"> Tambahkan ke Daftar Keinginan`,
        a9:`Berisi Iklan`,
        a10:`Tentang aplikasi ini <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Aplikasi porno terbaik untuk Android. Tonton video panas baru setiap hari 🔥
        <br>
        Hanya konten berkualitas tinggi, pemain tanpa jeda, pemuatan cepat, dan emosi tanpa akhir`,
        a12:`Diperbarui pada`,
        a13:`Keamanan data`,
        a14:`Pengembang dapat menampilkan informasi di sini tentang cara aplikasi mereka mengumpulkan dan menggunakan data Anda.`,
        a15:`Peringkat dan ulasan`,
        a16:`Peringkat dan ulasan diverifikasi <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K ulasan`,
        a18:`Sanjay Kumar`,
        a19:`Aplikasi ini sangat bagus! Kami sedang menunggu konten HOT baru!`,
        a20:`Eduard Tereshko`,
        a21:`Konten berkualitas tinggi! Setelah menonton video pertama, tidak mungkin berhenti di
        kedua`,
        a22:`Asha Devi`,
        a23:` Saya sangat menyukai aplikasi ini. `,
    },
    fil: {
        a1: `App Market`,
        a2: `XXXLOVE - ang pinakamahusay na porn app.`,
        a3: `PH Company`,
        a4: `48.7K review`,
        a5:`Mga Download`,
        a6:`Na-rate para sa 18+`,
        a7:`I-install`,
        a8:` <img src="/assets/images/bookmark.svg"> Idagdag sa Wishlist`,
        a9:`Naglalaman ng Mga Ad`,
        a10:`Tungkol sa app na ito <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Ang pinakamahusay na porn app para sa Android. Manood ng mga bagong maiinit na video araw-araw 🔥 🔥 🔥
        <br>
        Tanging ang mataas na kalidad na nilalaman, isang manlalaro na walang lags, mabilis na paglo-load at walang katapusang emosyon`,
        a12:`Na-update noong`,
        a13:`Kaligtasan ng data`,
        a14:`Maaaring magpakita ang mga developer ng impormasyon dito tungkol sa kung paano kinokolekta at ginagamit ng kanilang app ang iyong data.`,
        a15:`Mga rating at review`,
        a16:`Na-verify ang mga rating at review <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K review`,
        a18:`Sanjay Kumar`,
        a19:`Napakaganda ng app na ito! Naghihintay kami ng bagong HOT content!`,
        a20:`Eduard Tereshko`,
        a21:`Mataas na kalidad ng nilalaman! Pagkatapos panoorin ang unang video, imposibleng huminto sa
        ang pangalawa`,
        a22:`Asha Devi`,
        a23:` Talagang gusto ko ang app na ito. 💦💦💦 `,
    },
    ru: {
        a1: `Маркет приложений`,
        a2: `XXXLOVE - лучшее порноприложение`,
        a3: `PH Company`,
        a4: `48,7 тыс. отзывов`,
        a5:`Загрузки`,
        a6:`Рейтинг 18+`,
        a7:`Установить`,
        a8:` <img src="/assets/images/bookmark.svg"> Добавить в список желаний`,
        a9:`Содержит рекламу`,
        a10:`Об этом приложении <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Лучшее порноприложение для Android. Смотрите новые горячие видео каждый день 🔥 🔥 🔥
        <br>
        Только качественный контент, плеер без лагов, быстрая загрузка и бесконечные эмоции`,
        a12:`Обновлено`,
        a13:`Безопасность данных`,
        a14:`Разработчики могут показать здесь информацию о том, как их приложение собирает и использует ваши данные.`,
        a15:`Рейтинги и обзоры`,
        a16:`Рейтинги и отзывы проверены <img src="/assets/images/info.png" alt="">`,
        a17:`48,7 тыс. отзывов`,
        a18:`Петр Сипов`,
        a19:`Это приложение такое хорошее! Ждем новый ГОРЯЧИЙ контент!`,
        a20:`Эдуард Терешко`,
        a21:`Контент высокого качества! После просмотра первого видео невозможно остановиться на
        второй`,
        a22:`Анна Деви`,
        a23:` Мне очень нравится это приложение. 💦💦💦 `,
    },
    tr: {
        a1: "Uygulama Pazarı",
        a2: `XXXLOVE - en iyi porno uygulaması.`,
        a3: "PH Şirketi",
        a4: `48.7K inceleme`,
        a5:`İndirilenler`,
        a6: `18+' için derecelendirildi`,
        a7:`Yükle`,
        a8:` <img src="/assets/images/bookmark.svg"> İstek Listesine Ekle`,
        a9:`Reklam İçeriyor`,
        a10:`Bu uygulama hakkında <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Android için en iyi porno uygulaması. Her gün yeni sıcak videolar izleyin 🔥 🔥 🔥
        <br>
        Yalnızca yüksek kaliteli içerik, gecikmesiz bir oyuncu, hızlı yükleme ve sonsuz duygular`,
        a12:"Güncelleme tarihi",
        a13:`Veri güvenliği`,
        a14:`Geliştiriciler, uygulamalarının verilerinizi nasıl topladığı ve kullandığı hakkında bilgileri burada gösterebilir.`,
        a15:`Derecelendirmeler ve yorumlar`,
        a16:`Derecelendirmeler ve incelemeler doğrulandı <img src="/assets/images/info.png" alt=""> `,
        a17:`48.7K inceleme`,
        a18:`Sanjay Kumar`,
        a19:`Bu uygulama çok iyi! Yeni HOT içeriği bekliyoruz!`,
        a20:`Eduard Tereşko`,
        a21:`Yüksek kaliteli içerik! İlk videoyu izledikten sonra durmak imkansız
        ikinci`,
        a22:`Asha Devi`,
        a23:` Bu uygulamayı gerçekten seviyorum. 💦💦💦`,
    },
    ja: {
        a1: `アプリマーケット`,
        a2: `XXXLOVE-最高のポルノアプリ`,
        a3: `PH Company`,
        a4: `48.7Kレビュー`,
        a5: `ダウンロード`,
        a6: `18歳以上の評価`,
        a7: `インストール`,
        a8: `<img src =" /assets/images/bookmark.svg">ウィッシュリストに追加`,
        a9: `広告が含まれています`,
        a10: `このアプリについて <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Android向けの最高のポルノアプリ。毎日新しいホットな動画を見る🔥🔥🔥
        <br>
        高品質のコンテンツ,ラグのないプレーヤー,高速読み込み,無限の感情のみ`,
        a12: `更新日`,
        a13: `データの安全性`,
        a14: `開発者は,アプリがデータを収集して使用する方法に関する情報をここに表示できます。`,
        a15: `評価とレビュー`,
        a16:`評価とレビューが検証されます<imgsrc ="/assets/images/info.png "alt =" "> 1`,
        a17: `48.7Kレビュー`,
        a18: `Sanjay Kumar`,
        a19: `このアプリはとても良いです！新しいHOTコンテンツをお待ちしております！ `,
        a20: `Eduard Tereshko`,
        a21: `高品質のコンテンツ！最初のビデオを見た後,立ち寄ることは不可能です
        2番目の`,
        a22: `Asha Devi`,
        a23:`私は本当にこのアプリが大好きです。 💦💦💦`,
    },
    da: {
        a1: `App Market`,
        a2: `XXXLOVE - den bedste porno-app.`,
        a3: `PH Company`,
        a4: `48.7K anmeldelser`,
        a5: `Downloads`,
        a6:`Bedømt til 18+`,
        a7:`Installer`,
        a8:` <img src="/assets/images/bookmark.svg"> Tilføj til ønskeseddel`,
        a9:`Indeholder annoncer`,
        a10: `Om denne app <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: `Den bedste porno-app til Android. Se nye hotte videoer hver dag 🔥 🔥 🔥
        <br>
        Kun indhold af høj kvalitet, en spiller uden forsinkelser, hurtig indlæsning og endeløse følelser`,
        a12:`Opdateret den`,
        a13:`Datasikkerhed`,
        a14:`Udviklere kan her vise oplysninger om, hvordan deres app indsamler og bruger dine data.`,
        a15:`Bedømmelser og anmeldelser`,
        a16:`Bedømmelser og anmeldelser er bekræftet <img src="/assets/images/info.png" alt=""> `,
        a17:`48.7K anmeldelser`,
        a18:`Sanjay Kumar`,
        a19: `Denne app er så god! Vi venter på nyt HOT indhold!`,
        a20:`Eduard Tereshko`,
        a21: `Indhold af høj kvalitet! Efter at have set den første video, er det umuligt at stoppe ved
        den anden`,
        a22:`Asha Devi`,
        a23:` Jeg er virkelig vild med denne app. 💦💦💦 `,
    },
    ko: {
        a1: '앱 마켓',
        a2: `XXXLOVE - 최고의 포르노 앱`,
        a3: 'PH 회사',
        a4: `48.7K 리뷰`,
        a5:`다운로드`,
        a6:`18세 이상 등급`,
        a7:`설치`,
        a8:` <img src="/assets/images/bookmark.svg"> 위시리스트에 추가`,
        a9:`광고 포함`,
        a10:`이 앱 정보 <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Android용 최고의 포르노 앱입니다. 매일 새로운 핫 동영상을 시청하세요 🔥 🔥 🔥
        <br>
        고퀄리티 콘텐츠, 렉 없는 플레이어, 빠른 로딩, 끝없는 감성`,
        a12:`업데이트 날짜`,
        a13:`데이터 안전`,
        a14:`개발자는 앱에서 데이터를 수집하고 사용하는 방법에 대한 정보를 여기에 표시할 수 있습니다.`,
        a15:`평점 및 리뷰`,
        a16:`평가 및 리뷰가 확인되었습니다 <img src="/assets/images/info.png" alt=""> `,
        a17:`리뷰 48.7K`,
        a18:'산제이 쿠마르',
        a19:`이 앱은 정말 좋습니다! 새로운 HOT 콘텐츠를 기다리고 있습니다!`,
        a20:'에두아르드 테레시코',
        a21:`고품질 콘텐츠! 첫 번째 영상을 보고 나면 멈출 수 없는
        두 번째`,
        a22:'아샤 데비',
        a23:` 이 앱이 정말 마음에 듭니다. 💦💦💦 `,
    },
    it: {
        a1: 'App Market',
        a2: `XXXLOVE - la migliore app porno.`,
        a3: `Azienda PH`,
        a4: `48.7K recensioni`,
        a5: `Download`,
        a6:`Classificato per 18+`,
        a7:`Installa`,
        a8:` <img src="/assets/images/bookmark.svg"> Aggiungi alla lista dei desideri`,
        a9:`Contiene annunci`,
        a10: `Informazioni su questa app <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`La migliore app porno per Android. Guarda nuovi video hot ogni giorno 🔥 🔥 🔥
        <br>
        Solo contenuti di alta qualità, un giocatore senza ritardi, caricamento veloce ed emozioni infinite`,
        a12:`Aggiornato il`,
        a13:`Sicurezza dei dati`,
        a14:`Gli sviluppatori possono mostrare qui informazioni su come la loro app raccoglie e utilizza i tuoi dati.`,
        a15:`Valutazioni e recensioni`,
        a16:`Le valutazioni e le recensioni sono verificate <img src="/assets/images/info.png" alt=""> `,
        a17:`48.7K recensioni`,
        a18:`Sanjay Kumar`,
        a19:`Questa app è così buona! Stiamo aspettando nuovi contenuti HOT!`,
        a20:`Eduard Tereshko`,
        a21:`Contenuti di alta qualità! Dopo aver visto il primo video, è impossibile fermarsi
        il secondo`,
        a22:`Asha Devi`,
        a23:` Adoro questa app. 💦💦💦`,
    },
    no: {
        a1: `App Market`,
        a2: `XXXLOVE - den beste pornoappen.`,
        a3: `PH Company`,
        a4: `48.7K anmeldelser`,
        a5:`Nedlastinger`,
        a6:`Vurdert for 18+`,
        a7:`Installer`,
        a8:` <img src="/assets/images/bookmark.svg"> Legg til i ønskelisten`,
        a9:`Inneholder annonser`,
        a10: `Om denne appen <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Den beste pornoappen for Android. Se nye varme videoer hver dag 🔥 🔥 🔥
        <br>
        Bare innhold av høy kvalitet, en spiller uten forsinkelser, rask lasting og endeløse følelser`,
        a12:`Oppdatert på`,
        a13:`Datasikkerhet`,
        a14:`Utviklere kan vise informasjon her om hvordan appen deres samler inn og bruker dataene dine.`,
        a15:`Vurderinger og anmeldelser`,
        a16:`Vurderinger og anmeldelser er bekreftet <img src="/assets/images/info.png" alt=""> `,
        a17:`48.7K anmeldelser`,
        a18:`Sanjay Kumar`,
        a19: `Denne appen er så bra! Vi venter på nytt HOT innhold!`,
        a20:`Eduard Tereshko`,
        a21:`Innhold av høy kvalitet! Etter å ha sett den første videoen er det umulig å stoppe ved
        den andre`,
        a22:`Asha Devi`,
        a23:` Jeg elsker denne appen. 💦💦💦 `,
    },
    sv: {
        a1: `App Market`,
        a2: `XXXLOVE - den bästa porrappen.`,
        a3: `PH Company`,
        a4: `48.7K recensioner`,
        a5:`Nedladdningar`,
        a6:`Rättad för 18+`,
        a7:`Installera`,
        a8:` <img src="/assets/images/bookmark.svg"> Lägg till i önskelista`,
        a9:`Innehåller annonser`,
        a10:`Om den här appen <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Den bästa porrappen för Android. Se nya heta videor varje dag 🔥 🔥 🔥
        <br>
        Endast innehåll av hög kvalitet, en spelare utan fördröjningar, snabb laddning och oändliga känslor`,
        a12:`Uppdaterad den`,
        a13:`Datasäkerhet`,
        a14:`Utvecklare kan visa information här om hur deras app samlar in och använder din data.`,
        a15:`Betyg och recensioner`,
        a16:`Betyg och recensioner är verifierade <img src="/assets/images/info.png" alt=""> `,
        a17:`48.7K recensioner`,
        a18:`Sanjay Kumar`,
        a19:`Denna app är så bra! Vi väntar på nytt HOT innehåll!`,
        a20:`Eduard Tereshko`,
        a21:`Högkvalitativt innehåll! Efter att ha sett den första videon är det omöjligt att stanna vid
        den andra`,
        a22:`Asha Devi`,
        a23:` Jag älskar verkligen den här appen. 💦💦💦 `,
    },
    fi: {
        a1: "App Market",
        a2: `XXXLOVE - paras pornosovellus.`,
        a3: "PH Company",
        a4: "48,7 000 arvostelua",
        a5: "Lataukset",
        a6: "Arvioitu 18+",
        a7: "Asenna",
        a8:` <img src="/assets/images/bookmark.svg"> Lisää toivelistaan`,
        a9: "Sisältää mainoksia",
        a10: `Tietoja tästä sovelluksesta <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Paras pornosovellus Androidille. Katso uusia kuumia videoita joka päivä 🔥 🔥 🔥
        <br>
        Vain laadukas sisältö, soitin ilman viiveitä, nopea lataus ja loputtomat tunteet`,
        a12: "Päivitetty",
        a13: "Tietojen turvallisuus",
        a14:`Kehittäjät voivat näyttää täällä tietoja siitä, kuinka heidän sovelluksensa kerää ja käyttää tietojasi.`,
        a15: "Arviot ja arvostelut",
        a16:`Arviot ja arvostelut on vahvistettu <img src="/assets/images/info.png" alt=""> `,
        a17: "48,7 000 arvostelua",
        a18: "Sanjay Kumar",
        a19:`Tämä sovellus on niin hyvä! Odotamme uutta HOT sisältöä!`,
        a20: "Eduard Tereshko",
        a21: `Korkealaatuinen sisältö! Ensimmäisen videon katsomisen jälkeen on mahdotonta pysähtyä
        toinen`,
        a22: "Asha Devi",
        a23:` Rakastan todella tätä sovellusta. 💦💦💦 `,
    },
    is: {
        a1: `App Market`,
        a2: `XXXLOVE - besta klámforritið.`,
        a3: `PH Company`,
        a4: `48.7K umsagnir`,
        a5:`niðurhal`,
        a6:`Meinkunn fyrir 18+`,
        a7:`Setja upp`,
        a8:` <img src="/assets/images/bookmark.svg"> Setja á óskalista`,
        a9:`Inniheldur auglýsingar`,
        a10:`Um þetta forrit <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: `Besta klámforritið fyrir Android. Horfðu á ný heit myndbönd á hverjum degi 🔥 🔥 🔥
        <br>
        Aðeins hágæða efni, spilari án tafa, hröð hleðsla og endalausar tilfinningar`,
        a12:`Uppfært þann`,
        a13:`Gagnaöryggi`,
        a14:`Hönnuðir geta sýnt hér upplýsingar um hvernig appið þeirra safnar og notar gögnin þín.`,
        a15:`Einkunnir og umsagnir`,
        a16:`Einkunnir og umsagnir eru staðfestar <img src="/assets/images/info.png" alt=""> `,
        a17:`48.7K umsagnir`,
        a18:`Sanjay Kumar`,
        a19:`Þetta app er svo gott! Við bíðum eftir nýju HOT efni!`,
        a20:`Eduard Tereshko`,
        a21:`Hágæða efni! Eftir að hafa horft á fyrsta myndbandið er ómögulegt að stoppa við
        annað`,
        a22:`Asha Devi`,
        a23:` Ég elska þetta app. 💦💦💦 `,
    },
    el: {
        a1: "App Market",
        a2: `XXXLOVE - η καλύτερη εφαρμογή πορνό.`,
        a3: "PH Company",
        a4: "48,7 χιλιάδες κριτικές",
        a5: "Λήψεις",
        a6: "Βαθμολογήθηκε για 18+",
        a7: "Εγκατάσταση",
        a8:` <img src="/assets/images/bookmark.svg"> Προσθήκη στη λίστα επιθυμιών`,
        a9: "Περιέχει διαφημίσεις",
        a10: `Σχετικά με αυτήν την εφαρμογή <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: "Η καλύτερη εφαρμογή πορνό για Android. Παρακολουθήστε νέα καυτά βίντεο κάθε μέρα 🔥 🔥 🔥 <br> Μόνο περιεχόμενο υψηλής ποιότητας, παίκτης χωρίς καθυστερήσεις, γρήγορη φόρτωση και ατελείωτα συναισθήματα",
        a12: "Ενημερώθηκε στις",
        a13: "Ασφάλεια δεδομένων",
        a14:`Οι προγραμματιστές μπορούν να εμφανίσουν εδώ πληροφορίες σχετικά με τον τρόπο με τον οποίο η εφαρμογή τους συλλέγει και χρησιμοποιεί τα δεδομένα σας.`,
        a15: "Βαθμολογίες και κριτικές",
        a16:`Οι αξιολογήσεις και οι κριτικές επαληθεύονται <img src="/assets/images/info.png" alt=""> `,
        a17:`48,7 χιλιάδες κριτικές`,
        a18: "Σαντζάι Κουμάρ",
        a19: `Αυτή η εφαρμογή είναι τόσο καλή! Περιμένουμε νέο HOT περιεχόμενο!`,
        a20: "Eduard Tereshko",
        a21:`Περιεχόμενο υψηλής ποιότητας! Αφού παρακολουθήσετε το πρώτο βίντεο, είναι αδύνατο να σταματήσετε το δεύτερο`,
        a22: "Asha Devi",
        a23:` Μου αρέσει πολύ αυτή η εφαρμογή. 💦💦💦 `,
    },
    bg: {
        a1: `Пазар на приложения`,
        a2: `XXXLOVE - най-доброто порно приложение.`,
        a3: `PH Company`,
        a4: `48,7 хиляди отзиви`,
        a5:`Изтегляния`,
        a6:`Оценено за 18+`,
        a7: `Инсталиране`,
        a8:` <img src="/assets/images/bookmark.svg"> Добавяне към списък с желания`,
        a9: `Съдържа реклами`,
        a10:`За това приложение <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Най-доброто порно приложение за Android. Гледайте нови горещи видеоклипове всеки ден 🔥 🔥 🔥
        <br>
        Само висококачествено съдържание, плейър без забавяне, бързо зареждане и безкрайни емоции`,
        a12: `Актуализирано на`,
        a13:`Безопасност на данните`,
        a14:`Разработчиците могат да показват информация тук за това как тяхното приложение събира и използва вашите данни.`,
        a15:`Оценки и рецензии`,
        a16:`Оценките и рецензиите са проверени <img src="/assets/images/info.png" alt=""> `,
        a17:`48.7K отзиви`,
        a18: `Санджай Кумар`,
        a19:`Това приложение е толкова добро! Очакваме ново ГОРЕЩО съдържание!`,
        a20:`Едуард Терешко`,
        a21: `Висококачествено съдържание! След като гледате първото видео, е невъзможно да се спрете
        вторият`,
        a22:`Аша Деви`,
        a23: `Наистина обичам това приложение. 💦💦💦 `,
    },
    hu: {
        a1: "App Market",
        a2: "XXXLOVE – a legjobb pornóalkalmazás.",
        a3: "PH Company",
        a4: "48,7 ezer vélemény",
        a5: "Letöltések",
        a6: "18+ - ra értékelve",
        a7: "Telepítés",
        a8:` <img src="/assets/images/bookmark.svg"> Hozzáadás a kívánságlistához`,
        a9: "Hirdetéseket tartalmaz",
        a10: `Erről az alkalmazásról <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: "A legjobb pornóalkalmazás Androidra. Nézz meg minden nap új dögös videókat 🔥 🔥 🔥 <br>Csak kiváló minőségű tartalom, késések nélküli lejátszó, gyors betöltés és végtelen érzelmek",
        a12: "Frissítve",
        a13: "Adatbiztonság",
        a14: "A fejlesztők információkat jeleníthetnek meg itt arról, hogy alkalmazásuk hogyan gyűjti és használja fel az Ön adatait.",
        a15: "Értékelések és vélemények",
        a16:`Az értékelések és vélemények ellenőrizve <img src="/assets/images/info.png" alt=""> `,
        a17: "48,7 ezer vélemény",
        a18: "Sanjay Kumar",
        a19:` Ez az alkalmazás nagyon jó! Várjuk az új HOT tartalmakat!`,
        a20: "Eduard Tereshko",
        a21: `Kiváló minőségű tartalom! Az első videó megtekintése után lehetetlen megállni a második`,
        a22: "Asha Devi",
        a23:` Nagyon szeretem ezt az alkalmazást. 💦💦💦 `,
    },
    et: {
        a1: "App Market",
        a2: "XXXLOVE – parim pornorakendus.",
        a3: "PH ettevõte",
        a4: "48,7 tuhat arvustust",
        a5: "Allalaadimised",
        a6: "hinnatud vanusele 18+",
        a7: "Install",
        a8:` <img src="/assets/images/bookmark.svg"> Lisa sooviloendisse`,
        a9: "Sisaldab reklaame",
        a10: `Selle rakenduse kohta <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: "Parim pornorakendus Androidile. Vaadake iga päev uusi ägedaid videoid 🔥 🔥 🔥 <br> Ainult kvaliteetne sisu, viivitusteta mängija, kiire laadimine ja lõputud emotsioonid",
        a12: "Värskendatud",
        a13: "Andmete ohutus",
        a14: "Arendajad saavad siin näidata teavet selle kohta, kuidas nende rakendus teie andmeid kogub ja kasutab.",
        a15: "hinnangud ja arvustused",
        a16:`Hinnangud ja arvustused on kinnitatud <img src="/assets/images/info.png" alt=""> `,
        a17: "48,7 tuhat arvustust",
        a18: "Sanjay Kumar",
        a19:"See rakendus on nii hea! Ootame uut HOT sisu!",
        a20: "Eduard Tereshko",
        a21: "Kvaliteetne sisu! Pärast esimese video vaatamist on võimatu peatuda teine",
        a22: "Asha Devi",
        a23:` Ma tõesti armastan seda rakendust. 💦💦💦 `,
    },
    bn: {
        a1: 'অ্যাপ মার্কেট',
        a2: `XXXLOVE - সেরা পর্ণ অ্যাপ।`,
        a3: `PH কোম্পানি`,
        a4: `48.7K পর্যালোচনা`,
        a5:'ডাউনলোড',
        a6: `18+ ' এর জন্য রেট করা হয়েছে`,
        a7: 'ইনস্টল',
        a8:` <img src="/assets/images/bookmark.svg"> ইচ্ছা তালিকায় যোগ করুন`,
        a9: 'বিজ্ঞাপন রয়েছে',
        a10:'এই অ্যাপ সম্পর্কে <img class="arrow" src="/assets/images/arrow.svg" alt="">',
        a11: `Android এর জন্য সেরা পর্ণ অ্যাপ। প্রতিদিন নতুন নতুন হট ভিডিও দেখুন 🔥 🔥 🔥
        <br>
        শুধুমাত্র উচ্চ-মানের সামগ্রী, ল্যাগ ছাড়াই একটি প্লেয়ার, দ্রুত লোডিং এবং অন্তহীন আবেগ`,
        a12: `আপডেট করা হয়েছে`,
        a13: 'ডেটা নিরাপত্তা',
        a14: `ডেভেলপাররা তাদের অ্যাপ কীভাবে আপনার ডেটা সংগ্রহ করে এবং ব্যবহার করে সে সম্পর্কে তথ্য এখানে দেখাতে পারে।`,
        a15: `রেটিং এবং পর্যালোচনা`,
        a16:`রেটিং এবং পর্যালোচনা যাচাই করা হয়েছে <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K রিভিউ`,
        a18: 'সঞ্জয় কুমার',
        a19:'এই অ্যাপটি খুব ভাল! আমরা নতুন হট কন্টেন্টের জন্য অপেক্ষা করছি!',
        a20:'এডুয়ার্ড তেরেশকো',
        a21:`উচ্চ মানের সামগ্রী! প্রথম ভিডিওটি দেখার পরে, এটি থামানো অসম্ভব
        দ্বিতীয়`,
        a22:'আশা দেবী',
        a23:` আমি সত্যিই এই অ্যাপটি ভালোবাসি। 💦💦💦 `,
    },
    hi: {
        a1: `ऐप मार्केट`,
        a2: `XXXLOVE - सबसे अच्छा पोर्न ऐप।`,
        a3: `पीएच कंपनी`,
        a4: `48.7K समीक्षाएं`,
        a5: `डाउनलोड`,
        a6: `18+ के लिए रेटेड`,
        a7: `इंस्टॉल`,
        a8:` <img src="/assets/images/bookmark.svg"> विशलिस्ट में जोड़ें`,
        a9: `विज्ञापन शामिल हैं`,
        a10: `इस ऐप के बारे में <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: `एंड्रॉइड के लिए सबसे अच्छा पोर्न ऐप। हर दिन नए हॉट वीडियो देखें
        <br>
        केवल उच्च-गुणवत्ता वाली सामग्री, बिना अंतराल वाला खिलाड़ी, तेज़ लोडिंग और अंतहीन भावनाएं`,
        a12: `अपडेट किया गया`,
        a13: `डेटा सुरक्षा`,
        a14: `डेवलपर्स यहां इस बारे में जानकारी दिखा सकते हैं कि उनका ऐप कैसे आपका डेटा एकत्र करता है और उसका उपयोग करता है।`,
        a15:`रेटिंग और समीक्षाएं`,
        a16:`रेटिंग और समीक्षाएं सत्यापित हैं <img src="/assets/images/info.png" alt=""> `,
        a17: `48.7K समीक्षाएं`,
        a18: `संजय कुमार`,
        a19: `यह ऐप बहुत अच्छा है! हम नई HOT सामग्री की प्रतीक्षा कर रहे हैं!`,
        a20:`एडुआर्ड टेरेश्को`,
        a21: `उच्च गुणवत्ता वाली सामग्री! पहला वीडियो देखने के बाद यहां रुकना नामुमकिन है
        दूसरा`,
        a22: `आशा देवी`,
        a23:` मुझे यह ऐप बहुत पसंद है। `,
    },
    hr: {
        a1: `App Market`,
        a2: `XXXLOVE - najbolja porno aplikacija.`,
        a3: `PH Company`,
        a4: "48,7 tisuća recenzija",
        a5:`Preuzimanja`,
        a6:`Ocijenjeno za 18+`,
        a7:`Instaliraj`,
        a8:` <img src="/assets/images/bookmark.svg"> Dodaj na listu želja`,
        a9:`Sadrži oglase`,
        a10:`O ovoj aplikaciji <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: `Najbolja porno aplikacija za Android. Gledajte nove vruće videe svaki dan 🔥 🔥 🔥
        <br>
        Samo visokokvalitetan sadržaj, igrač bez zaostajanja, brzo učitavanje i beskrajne emocije`,
        a12:`Ažurirano`,
        a13: `Sigurnost podataka`,
        a14:`Razvojni programeri ovdje mogu prikazati informacije o tome kako njihova aplikacija prikuplja i koristi vaše podatke.`,
        a15:`Ocjene i recenzije`,
        a16:`Ocjene i recenzije su provjerene <img src="/assets/images/info.png" alt=""> `,
        a17:`48,7 tisuća recenzija`,
        a18:`Sanjay Kumar`,
        a19:`Ova je aplikacija tako dobra! Čekamo novi HOT sadržaj!`,
        a20:`Eduard Tereško`,
        a21:`Visoka kvaliteta sadržaja! Nakon što pogledate prvi video, nemoguće je zastati
        drugi`,
        a22:`Asha Devi`,
        a23:` Stvarno volim ovu aplikaciju. 💦💦💦 `,
    },
    sl: {
        a1: 'App Market',
        a2: `XXXLOVE - najboljša porno aplikacija.`,
        a3: 'PH Company',
        a4: "48,7 tisoč ocen",
        a5: `Prenosi`,
        a6: `Ocenjeno za 18+`,
        a7: `Namesti`,
        a8:` <img src="/assets/images/bookmark.svg"> Dodaj na seznam želja`,
        a9: `Vsebuje oglase`,
        a10: `O tej aplikaciji <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: `Najboljša porno aplikacija za Android. Vsak dan si oglejte nove vroče videoposnetke 🔥 🔥 🔥
        <br>
        Samo visokokakovostna vsebina, predvajalnik brez zamikov, hitro nalaganje in neskončna čustva`,
        a12: `Posodobljeno`,
        a13: `Varnost podatkov`,
        a14:`Razvijalci lahko tukaj prikažejo informacije o tem, kako njihova aplikacija zbira in uporablja vaše podatke.`,
        a15: `Ocene in ocene`,
        a16:`Ocene in ocene so preverjene <img src="/assets/images/info.png" alt=""> `,
        a17: "48,7 tisoč ocen",
        a18: `Sanjay Kumar`,
        a19: `Ta aplikacija je tako dobra! Čakamo na nove HOT vsebine!`,
        a20: `Eduard Tereško`,
        a21: `Visokokakovostna vsebina! Po ogledu prvega videa se je nemogoče ustaviti
        drugi`,
        a22: `Asha Devi`,
        a23:` Resnično mi je všeč ta aplikacija. 💦💦💦 `,
    },
     ro: {
        a1: `Piata de aplicații`,
        a2: `XXXLOVE - cea mai bună aplicație porno.`,
        a3: `Compania PH`,
        a4: `48.7K recenzii`,
        a5:`Descărcări`,
        a6:`Evaluat pentru 18+`,
        a7:`Instalare`,
        a8:` <img src="/assets/images/bookmark.svg"> Adaugă la lista de dorințe`,
        a9:`Conține reclame`,
        a10:`Despre această aplicație <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Cea mai bună aplicație porno pentru Android. Urmărește videoclipuri noi în fiecare zi 🔥 🔥 🔥
        <br>
        Doar conținut de înaltă calitate, un jucător fără întârzieri, încărcare rapidă și emoții nesfârșite`,
        a12:`Actualizat pe`,
        a13:`Siguranța datelor`,
        a14:`Dezvoltatorii pot afișa aici informații despre modul în care aplicația lor colectează și utilizează datele dvs.`,
        a15:`Evaluări și recenzii`,
        a16:`Evaluările și recenziile sunt verificate <img src="/assets/images/info.png" alt="">`,
        a17:`48.7K recenzii`,
        a18:`Sanjay Kumar`,
        a19:`Această aplicație este atât de bună! Așteptăm conținut nou HOT!`,
        a20:`Eduard Tereshko`,
        a21:`Conținut de înaltă calitate! După vizionarea primului videoclip, este imposibil să te oprești la
        al doilea`,
        a22:`Asha Devi`,
        a23:` Îmi place foarte mult această aplicație. 💦💦💦 `,
    },
    cs: {
        a1: "App Market",
        a2: `XXXLOVE – nejlepší porno aplikace.`,
        a3: "PH Company",
        a4: `48,7 tisíc recenzí`,
        a5: "Stahování",
        a6: "Hodnocení pro 18+",
        a7: "Instalovat",
        a8:` <img src="/assets/images/bookmark.svg"> Přidat do seznamu přání`,
        a9:`Obsahuje reklamy`,
        a10:`O této aplikaci <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11:`Nejlepší porno aplikace pro Android. Sledujte každý den nová žhavá videa 🔥 🔥 🔥
        <br>
        Pouze vysoce kvalitní obsah, přehrávač bez lagů, rychlé načítání a nekonečné emoce`,
        a12:`Aktualizováno dne`,
        a13:`Bezpečnost dat`,
        a14:`Vývojáři zde mohou zobrazit informace o tom, jak jejich aplikace shromažďuje a používá vaše data.`,
        a15:`Hodnocení a recenze`,
        a16:`Hodnocení a recenze jsou ověřeny <img src="/assets/images/info.png" alt=""> `,
        a17:`48,7 tisíc recenzí`,
        a18: "Sanjay Kumar",
        a19: `Tato aplikace je tak dobrá! Čekáme na nový HOT obsah!`,
        a20: "Eduard Tereshko",
        a21:`Vysoce kvalitní obsah! Po shlédnutí prvního videa se nelze zastavit
        druhý`,
        a22: "Asha Devi",
        a23:` Tuto aplikaci opravdu miluji. 💦💦💦 `,
    },
    pl: {
        a1: `Rynek aplikacji`,
        a2: `XXXLOVE - najlepsza aplikacja pornograficzna`,
        a3: `Firma PH`,
        a4: `48,7 tys. recenzji`,
        a5: `Do pobrania`,
        a6: `Ocenione na 18+`,
        a7:`Zainstaluj`,
        a8:` <img src="/assets/images/bookmark.svg"> Dodaj do listy życzeń`,
        a9: `Zawiera reklamy`,
        a10: `O tej aplikacji <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: `Najlepsza aplikacja porno na Androida. Oglądaj codziennie nowe gorące filmy 🔥 🔥 🔥
        <br>
        Tylko wysokiej jakości treści, odtwarzacz bez lagów, szybkie ładowanie i niekończące się emocje`,
        a12:`Zaktualizowano`,
        a13: `Bezpieczeństwo danych`,
        a14:`Programiści mogą tutaj wyświetlać informacje o tym, jak ich aplikacja zbiera i wykorzystuje Twoje dane.`,
        a15:`Oceny i recenzje`,
        a16:`Oceny i recenzje są weryfikowane <img src="/assets/images/info.png" alt=""> `,
        a17: `48,7 tys. recenzji`,
        a18: `Sanjay Kumar`,
        a19: `Ta aplikacja jest tak dobra! Czekamy na nową zawartość HOT!`,
        a20: `Eduard Tereshko`,
        a21:`Zawartość wysokiej jakości! Po obejrzeniu pierwszego filmu nie można się zatrzymać na
        drugi`,
        a22: `Asha Devi`,
        a23:` Naprawdę kocham tę aplikację. `,
    },
    vi: {
        a1: `Thị trường ứng dụng`,
        a2: `XXXLOVE - ứng dụng khiêu dâm tốt nhất.`,
        a3: `Công ty PH`,
        a4: `48,7 nghìn lượt đánh giá`,
        a5: `Tải xuống`,
        a6: `Được đánh giá cho 18 + `,
        a7: `Cài đặt`,
        a8: `<img src ="/assets/images/bookmark.svg"> Thêm vào danh sách yêu thích`,
        a9: `Chứa quảng cáo`,
        a10: `Giới thiệu về ứng dụng này <img class="arrow" src="/assets/images/arrow.svg" alt="">`,
        a11: `Ứng dụng khiêu dâm tốt nhất dành cho Android. Xem video mới hot mỗi ngày 🔥 🔥 🔥
        <br>
        Chỉ nội dung chất lượng cao, trình phát không có độ trễ, tải nhanh và cảm xúc bất tận`,
        a12: `Cập nhật vào`,
        a13: `An toàn dữ liệu`,
        a14: `Các nhà phát triển có thể hiển thị thông tin ở đây về cách ứng dụng của họ thu thập và sử dụng dữ liệu của bạn.`,
        a15: `Xếp hạng và đánh giá`,
        a16: `Xếp hạng và bài đánh giá đã được xác minh <img src ="/assets/images/info.png "alt =" ">`,
        a17: `48,7 nghìn lượt đánh giá`,
        a18: `Sanjay Kumar`,
        a19: `Ứng dụng này quá tốt! Chúng tôi đang chờ đợi những nội dung HOT mới!`,
        a20: ` Eduard Tereshko`,
        a21: `Nội dung chất lượng cao! Sau khi xem video đầu tiên, không thể dừng lại ở
        thứ hai`,
        a22: `Asha Devi`,
        a23: `Tôi thực sự thích ứng dụng này. 💦💦💦 `,
    },
};

function translate() {
    var detected_language = detect_language();
    for (y in translation["source"]) {
        replace_text(detected_language, y);

    }

}
window.onload = translate()